name: tsp-analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - jupyterlab
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - networkx
  - tqdm
  - ipywidgets
  - plotly
  - nbformat
  - pip
  - pip:
    - jupyter-dash
